### PR TITLE
EN-62054: openapi server gen mvp

### PR DESCRIPTION
**Pull request by PaulMTT**
This wires up openapi server generation. Although this is a mvp and not redshift specific, that will come next. 

Specifically we are targeting Jakarta, and generating interfaces only.

The generated interfaces will be annotated with their rest configurations `@Path ...etc`, and by implementing this interface and annotating your implementation with `@ApplicationScoped`, you will have a working rest server.

Workflow as follows:
1. Get a openapi spec, and place it somewhere (we have chosen `src/main/resources/xxx`
2. Run the maven generate target, this will generate classes from the openapi spec
3. Once generated, you can implement the various interfaces. Once an endpoint interface is implemented, this endpoint will be available.
4. Explore via devui, checkout smallrye/swagger sections

### CODE REVIEW

**Comment by PaulMTT** [comment]
image

**Review by dnabilali — APPROVED** [review]

**Comment by PaulMTT** [comment]
For Lombok support I have configured the openapi generator to add additional annotations:
```
<additionalModelTypeAnnotations>
  @lombok.Data
  @lombok.AllArgsConstructor
  @lombok.NoArgsConstructor
  @lombok.Builder
</additionalModelTypeAnnotations>
```

The delombok plugin will then source these generated files and generate plain old java(turns Lombok annotations into hard java code).
This plan java, located in `generated-sources/delombok` will then be attached as source roots for the main project to use.

**Comment by PaulMTT** [comment]
Lombok removed.
API endpoints created to the best of my abilities according to the existing api.
Not 100% complete...like the new-query stuff, or more detailed query response column value types.
But this is a good start to organize a base around.

I have disabled openapi scanning, and instead specified to serve our static openapi.yaml asset.

**Comment by PaulMTT** [comment]
This is our openapi spec in yaml format:
https://github.com/socrata-platform/soql-redshift-adapter/blob/3bfe9a9feca928b3cd608d80918fd1adad89859a/src/main/resources/META-INF/openapi.yaml

**Review by zachlefevre — APPROVED** [review]

**Pull request merged**
